import JSZip from 'jszip';
import { NextJsFile } from '../types';

export const NEXTJS_REPO_FILES: NextJsFile[] = [
  {
    path: 'package.json',
    description: 'Konfigurasi dependencies Next.js, React, TypeScript, Tailwind CSS, & Lucide React',
    language: 'json',
    content: [
      '{',
      '  "name": "sweepinganku-nextjs",',
      '  "version": "1.0.0",',
      '  "private": true,',
      '  "scripts": {',
      '    "dev": "next dev",',
      '    "build": "next build",',
      '    "start": "next start",',
      '    "lint": "next lint"',
      '  },',
      '  "dependencies": {',
      '    "react": "^19.0.0",',
      '    "react-dom": "^19.0.0",',
      '    "next": "^15.1.0",',
      '    "lucide-react": "^0.469.0",',
      '    "clsx": "^2.1.1",',
      '    "tailwind-merge": "^2.6.0"',
      '  },',
      '  "devDependencies": {',
      '    "typescript": "^5.7.2",',
      '    "@types/node": "^22.10.2",',
      '    "@types/react": "^19.0.2",',
      '    "@types/react-dom": "^19.0.2",',
      '    "postcss": "^8.4.49",',
      '    "tailwindcss": "^3.4.17",',
      '    "eslint": "^9.17.0",',
      '    "eslint-config-next": "^15.1.0"',
      '  }',
      '}'
    ].join('\n')
  },
  {
    path: 'app/layout.tsx',
    description: 'Root Layout Next.js App Router dengan metadata dan styling global',
    language: 'tsx',
    content: [
      'import type { Metadata } from "next";',
      'import { Inter } from "next/font/google";',
      'import "./globals.css";',
      '',
      'const inter = Inter({ subsets: ["latin"] });',
      '',
      'export const metadata: Metadata = {',
      '  title: "Sweepinganku — Surgical Sweeping Manager",',
      '  description: "Aplikasi manajemen sweeping pasien bedah harian, generator laporan WhatsApp per-DPJP dan divisi, serta rekap mingguan.",',
      '};',
      '',
      'export default function RootLayout({',
      '  children,',
      '}: Readonly<{',
      '  children: React.ReactNode;',
      '}>) {',
      '  return (',
      '    <html lang="id">',
      '      <body className={inter.className + " bg-slate-50 text-slate-900 min-h-screen antialiased"}>',
      '        {children}',
      '      </body>',
      '    </html>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'app/page.tsx',
    description: 'Halaman Utama Next.js App Router (Dashboard Sweepinganku)',
    language: 'tsx',
    content: [
      "'use client';",
      '',
      "import { useState, useEffect, useMemo } from 'react';",
      "import { DIVISIONS, DEFAULT_ROOMS } from '@/lib/constants';",
      "import { Patient, ViewMode } from '@/types';",
      "import { loadPatients, savePatients, today, formatIndonesianDate, getKoasName, setKoasName } from '@/lib/storage';",
      "import { Navbar } from '@/components/Navbar';",
      "import { ControlsBar } from '@/components/ControlsBar';",
      "import { PatientCard } from '@/components/PatientCard';",
      "import { PatientModal } from '@/components/PatientModal';",
      "import { ReportModal } from '@/components/ReportModal';",
      "import { WeeklyModal } from '@/components/WeeklyModal';",
      "import { Users, Bed, Stethoscope } from 'lucide-react';",
      '',
      'export default function HomePage() {',
      "  const [date, setDate] = useState<string>('');",
      '  const [division, setDivision] = useState<string>(DIVISIONS[0]);',
      '  const [patients, setPatients] = useState<Patient[]>([]);',
      "  const [view, setView] = useState<ViewMode>('dpjp');",
      "  const [selectedDpjp, setSelectedDpjp] = useState<string>('');",
      "  const [searchQuery, setSearchQuery] = useState<string>('');",
      "  const [koasName, setKoasNameState] = useState<string>('dr. Muda / Koas Bedah');",
      '',
      '  const [patientModalOpen, setPatientModalOpen] = useState(false);',
      '  const [editingPatient, setEditingPatient] = useState<Patient | null>(null);',
      '  const [reportModalOpen, setReportModalOpen] = useState(false);',
      "  const [reportMode, setReportMode] = useState<'dpjp' | 'all'>('dpjp');",
      '  const [weeklyModalOpen, setWeeklyModalOpen] = useState(false);',
      '',
      '  useEffect(() => {',
      '    const t = today();',
      '    setDate(t);',
      '    setKoasNameState(getKoasName());',
      '    const initial = loadPatients(t, DIVISIONS[0]);',
      '    setPatients(initial);',
      '  }, []);',
      '',
      '  const handleDateOrDivisionChange = (newDate: string, newDiv: string) => {',
      '    setDate(newDate);',
      '    setDivision(newDiv);',
      "    setSelectedDpjp('');",
      '    const loaded = loadPatients(newDate, newDiv);',
      '    setPatients(loaded);',
      '  };',
      '',
      '  const dpjps = useMemo(() => {',
      '    return [...new Set(patients.map(p => p.dpjp).filter(Boolean))].sort();',
      '  }, [patients]);',
      '',
      '  useEffect(() => {',
      '    if (!selectedDpjp && dpjps.length > 0) {',
      '      setSelectedDpjp(dpjps[0]);',
      '    } else if (dpjps.length > 0 && !dpjps.includes(selectedDpjp)) {',
      '      setSelectedDpjp(dpjps[0]);',
      '    }',
      '  }, [dpjps, selectedDpjp]);',
      '',
      '  const activeRooms = useMemo(() => {',
      '    const patientRooms = [...new Set(patients.map(p => p.room))];',
      '    return [',
      '      ...DEFAULT_ROOMS.filter(r => patientRooms.includes(r)),',
      '      ...patientRooms.filter(r => !DEFAULT_ROOMS.includes(r))',
      '    ];',
      '  }, [patients]);',
      '',
      '  const filteredPatients = useMemo(() => {',
      '    let result = patients;',
      "    if (view === 'dpjp' && selectedDpjp) {",
      '      result = result.filter(p => p.dpjp === selectedDpjp);',
      '    }',
      '    if (searchQuery.trim()) {',
      '      const q = searchQuery.toLowerCase();',
      '      result = result.filter(',
      '        p =>',
      '          p.name.toLowerCase().includes(q) ||',
      '          p.rm.toLowerCase().includes(q) ||',
      '          p.dx.toLowerCase().includes(q) ||',
      '          p.room.toLowerCase().includes(q) ||',
      '          p.kamar.toLowerCase().includes(q)',
      '      );',
      '    }',
      '    return result;',
      '  }, [patients, view, selectedDpjp, searchQuery]);',
      '',
      '  const handleSavePatient = (saved: Patient) => {',
      '    const exists = patients.some(p => p.id === saved.id);',
      '    let updated: Patient[];',
      '    if (exists) {',
      '      updated = patients.map(p => (p.id === saved.id ? saved : p));',
      '    } else {',
      '      updated = [...patients, saved];',
      '    }',
      '    setPatients(updated);',
      '    savePatients(date, division, updated);',
      '    setPatientModalOpen(false);',
      '    setEditingPatient(null);',
      '  };',
      '',
      '  const handleDeletePatient = (id: string) => {',
      "    if (confirm('Hapus pasien ini dari daftar sweeping?')) {",
      '      const updated = patients.filter(p => p.id !== id);',
      '      setPatients(updated);',
      '      savePatients(date, division, updated);',
      '    }',
      '  };',
      '',
      '  return (',
      '    <div className="min-h-screen flex flex-col bg-slate-50 text-slate-900">',
      '      <Navbar',
      '        koasName={koasName}',
      '        onUpdateKoasName={(name) => {',
      '          setKoasName(name);',
      '          setKoasNameState(name);',
      '        }}',
      '        onAddPatient={() => {',
      '          setEditingPatient(null);',
      '          setPatientModalOpen(true);',
      '        }}',
      '      />',
      '',
      '      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 space-y-6">',
      '        <ControlsBar',
      '          date={date}',
      '          division={division}',
      '          divisions={DIVISIONS}',
      '          onDateChange={(d) => handleDateOrDivisionChange(d, division)}',
      '          onDivisionChange={(div) => handleDateOrDivisionChange(date, div)}',
      '          searchQuery={searchQuery}',
      '          onSearchChange={setSearchQuery}',
      '          onOpenReport={(mode) => {',
      '            setReportMode(mode);',
      '            setReportModalOpen(true);',
      '          }}',
      '          onOpenWeekly={() => setWeeklyModalOpen(true)}',
      '        />',
      '',
      '        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-4">',
      '          <div>',
      '            <div className="text-xs font-semibold text-blue-600 uppercase tracking-wider">',
      '              {division}',
      '            </div>',
      '            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">',
      '              Dashboard Sweeping · {formatIndonesianDate(date)}',
      '            </h1>',
      '          </div>',
      '          <div className="flex items-center gap-3">',
      '            <div className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-lg border border-slate-200 shadow-sm text-xs text-slate-600">',
      '              <Users className="w-4 h-4 text-blue-600" />',
      '              <span><b>{patients.length}</b> Pasien</span>',
      '            </div>',
      '            <div className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-lg border border-slate-200 shadow-sm text-xs text-slate-600">',
      '              <Stethoscope className="w-4 h-4 text-emerald-600" />',
      '              <span><b>{dpjps.length}</b> DPJP</span>',
      '            </div>',
      '            <div className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-lg border border-slate-200 shadow-sm text-xs text-slate-600">',
      '              <Bed className="w-4 h-4 text-purple-600" />',
      '              <span><b>{new Set(patients.map(p => p.room)).size}</b> Ruangan</span>',
      '            </div>',
      '          </div>',
      '        </div>',
      '',
      '        <div className="flex items-center gap-2">',
      '          <button',
      "            onClick={() => setView('dpjp')}",
      '            className={"px-4 py-2 rounded-lg text-sm font-semibold transition-colors " + (view === "dpjp" ? "bg-blue-600 text-white shadow-sm" : "bg-white text-slate-600 border border-slate-200 hover:bg-slate-100")}',
      '          >',
      '            Fokus Per-DPJP',
      '          </button>',
      '          <button',
      "            onClick={() => setView('all')}",
      '            className={"px-4 py-2 rounded-lg text-sm font-semibold transition-colors " + (view === "all" ? "bg-blue-600 text-white shadow-sm" : "bg-white text-slate-600 border border-slate-200 hover:bg-slate-100")}',
      '          >',
      '            Seluruh Ruangan Divisi',
      '          </button>',
      '        </div>',
      '',
      '        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">',
      '          <aside className="lg:col-span-1 space-y-4">',
      '            {view === "dpjp" ? (',
      '              <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">',
      '                <div className="flex items-center justify-between mb-3">',
      '                  <h3 className="font-bold text-sm text-slate-800">Daftar DPJP</h3>',
      '                  <span className="text-xs bg-slate-100 text-slate-600 px-2 py-0.5 rounded-full font-medium">',
      '                    {dpjps.length} dokter',
      '                  </span>',
      '                </div>',
      '                {dpjps.length === 0 ? (',
      '                  <p className="text-xs text-slate-500 py-3 text-center">Belum ada DPJP terdaftar hari ini.</p>',
      '                ) : (',
      '                  <div className="space-y-1">',
      '                    {dpjps.map((d) => {',
      '                      const count = patients.filter(p => p.dpjp === d).length;',
      '                      const active = d === selectedDpjp;',
      '                      return (',
      '                        <button',
      '                          key={d}',
      '                          onClick={() => setSelectedDpjp(d)}',
      '                          className={"w-full text-left px-3 py-2.5 rounded-lg text-xs font-semibold flex items-center justify-between transition-all " + (active ? "bg-blue-50 text-blue-700 border border-blue-200 shadow-sm" : "text-slate-700 hover:bg-slate-50 border border-transparent")}',
      '                        >',
      '                          <span className="truncate pr-2">{d}</span>',
      '                          <span className={"text-[11px] px-2 py-0.5 rounded-full " + (active ? "bg-blue-200 text-blue-800" : "bg-slate-100 text-slate-600")}>',
      '                            {count}',
      '                          </span>',
      '                        </button>',
      '                      );',
      '                    })}',
      '                  </div>',
      '                )}',
      '              </div>',
      '            ) : (',
      '              <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">',
      '                <h3 className="font-bold text-sm text-slate-800 mb-2">Mode Seluruh Divisi</h3>',
      '                <p className="text-xs text-slate-500 leading-relaxed">',
      '                  Menampilkan seluruh pasien divisi <b>{division}</b> dikelompokkan berdasarkan ruangan rawat inap.',
      '                </p>',
      '              </div>',
      '            )}',
      '          </aside>',
      '',
      '          <div className="lg:col-span-3 space-y-4">',
      '            {activeRooms.length === 0 && filteredPatients.length === 0 ? (',
      '              <div className="bg-white rounded-xl border border-dashed border-slate-300 p-12 text-center">',
      '                <Users className="w-12 h-12 text-slate-300 mx-auto mb-3" />',
      '                <h3 className="font-bold text-slate-700">Belum ada pasien terdaftar</h3>',
      '                <p className="text-xs text-slate-500 mt-1 max-w-sm mx-auto">',
      '                  Mulai sweeping dengan mengklik tombol "+ Tambah Pasien".',
      '                </p>',
      '              </div>',
      '            ) : (',
      '              activeRooms.map((roomName) => {',
      '                const roomPatients = filteredPatients.filter(p => p.room === roomName);',
      '                if (roomPatients.length === 0 && view === "dpjp") return null;',
      '                return (',
      '                  <section key={roomName} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">',
      '                    <div className="px-4 py-3 bg-slate-50/75 border-b border-slate-200 flex items-center justify-between">',
      '                      <div className="flex items-center gap-2">',
      '                        <Bed className="w-4 h-4 text-slate-500" />',
      '                        <span className="font-bold text-sm text-slate-800">{roomName}</span>',
      '                      </div>',
      '                      <span className="text-xs font-semibold text-slate-500">',
      '                        {roomPatients.length} pasien',
      '                      </span>',
      '                    </div>',
      '                    <div className="p-4">',
      '                      {roomPatients.length === 0 ? (',
      '                        <p className="text-xs text-slate-400 italic py-2">Tidak ada pasien di ruangan ini.</p>',
      '                      ) : (',
      '                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">',
      '                          {roomPatients.map((patient) => (',
      '                            <PatientCard',
      '                              key={patient.id}',
      '                              patient={patient}',
      '                              onEdit={() => {',
      '                                setEditingPatient(patient);',
      '                                setPatientModalOpen(true);',
      '                              }}',
      '                              onDelete={() => handleDeletePatient(patient.id)}',
      '                            />',
      '                          ))}',
      '                        </div>',
      '                      )}',
      '                    </div>',
      '                  </section>',
      '                );',
      '              })',
      '            )}',
      '          </div>',
      '        </div>',
      '      </main>',
      '',
      '      <PatientModal',
      '        isOpen={patientModalOpen}',
      '        initialData={editingPatient}',
      '        defaultDpjp={selectedDpjp}',
      '        existingDpjps={dpjps}',
      '        onClose={() => {',
      '          setPatientModalOpen(false);',
      '          setEditingPatient(null);',
      '        }}',
      '        onSave={handleSavePatient}',
      '      />',
      '',
      '      <ReportModal',
      '        isOpen={reportModalOpen}',
      '        mode={reportMode}',
      '        date={date}',
      '        division={division}',
      '        koasName={koasName}',
      '        selectedDpjp={selectedDpjp}',
      '        patients={patients}',
      '        onClose={() => setReportModalOpen(false)}',
      '      />',
      '',
      '      <WeeklyModal',
      '        isOpen={weeklyModalOpen}',
      '        currentDate={date}',
      '        division={division}',
      '        onClose={() => setWeeklyModalOpen(false)}',
      '      />',
      '    </div>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'app/globals.css',
    description: 'Styling global Tailwind CSS Next.js',
    language: 'css',
    content: [
      '@tailwind base;',
      '@tailwind components;',
      '@tailwind utilities;',
      '',
      ':root {',
      '  --background: #f8fafc;',
      '  --foreground: #0f172a;',
      '}',
      '',
      'body {',
      '  color: var(--foreground);',
      '  background: var(--background);',
      '}'
    ].join('\n')
  },
  {
    path: 'components/Navbar.tsx',
    description: 'Komponen Topbar Navbar dengan profil koas & tombol tambah pasien',
    language: 'tsx',
    content: [
      "'use client';",
      '',
      "import { useState } from 'react';",
      "import { Plus, UserCheck, Stethoscope, Edit2, Check } from 'lucide-react';",
      '',
      'interface NavbarProps {',
      '  koasName: string;',
      '  onUpdateKoasName: (name: string) => void;',
      '  onAddPatient: () => void;',
      '}',
      '',
      'export function Navbar({ koasName, onUpdateKoasName, onAddPatient }: NavbarProps) {',
      '  const [isEditingKoas, setIsEditingKoas] = useState(false);',
      '  const [tempName, setTempName] = useState(koasName);',
      '',
      '  return (',
      '    <header className="sticky top-0 z-30 bg-white border-b border-slate-200 shadow-xs">',
      '      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between gap-4">',
      '        <div className="flex items-center gap-3">',
      '          <div className="w-10 h-10 rounded-xl bg-blue-600 flex items-center justify-center text-white shadow-sm">',
      '            <Stethoscope className="w-6 h-6" />',
      '          </div>',
      '          <div>',
      '            <div className="font-extrabold text-lg text-slate-900 leading-tight">',
      '              Sweepinganku',
      '            </div>',
      '            <div className="text-[11px] font-medium text-slate-500">',
      '              Surgical Sweeping Manager & WhatsApp Generator',
      '            </div>',
      '          </div>',
      '        </div>',
      '',
      '        <div className="flex items-center gap-3">',
      '          <div className="hidden sm:flex items-center gap-2 bg-slate-50 border border-slate-200 px-3 py-1.5 rounded-lg text-xs">',
      '            <UserCheck className="w-3.5 h-3.5 text-blue-600" />',
      '            {isEditingKoas ? (',
      '              <div className="flex items-center gap-1.5">',
      '                <input',
      '                  type="text"',
      '                  value={tempName}',
      '                  onChange={(e) => setTempName(e.target.value)}',
      '                  placeholder="Nama Koas..."',
      '                  className="px-2 py-0.5 bg-white border border-slate-300 rounded text-xs outline-none focus:border-blue-500"',
      '                />',
      '                <button',
      '                  onClick={() => {',
      '                    onUpdateKoasName(tempName);',
      '                    setIsEditingKoas(false);',
      '                  }}',
      '                  className="p-1 hover:bg-emerald-50 text-emerald-600 rounded"',
      '                >',
      '                  <Check className="w-3.5 h-3.5" />',
      '                </button>',
      '              </div>',
      '            ) : (',
      '              <div className="flex items-center gap-1.5">',
      '                <span className="font-medium text-slate-700">{koasName}</span>',
      '                <button',
      '                  onClick={() => {',
      '                    setTempName(koasName);',
      '                    setIsEditingKoas(true);',
      '                  }}',
      '                  className="text-slate-400 hover:text-slate-600"',
      '                  title="Ganti Nama Koas"',
      '                >',
      '                  <Edit2 className="w-3 h-3" />',
      '                </button>',
      '              </div>',
      '            )}',
      '          </div>',
      '',
      '          <button',
      '            onClick={onAddPatient}',
      '            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs sm:text-sm px-3.5 py-2 rounded-lg shadow-sm transition-colors"',
      '          >',
      '            <Plus className="w-4 h-4" />',
      '            <span>Tambah Pasien</span>',
      '          </button',
      '        </div>',
      '      </div>',
      '    </header>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'components/ControlsBar.tsx',
    description: 'Komponen filter tanggal, divisi bedah, pencarian, dan tombol aksi WA & Rekap',
    language: 'tsx',
    content: [
      "'use client';",
      '',
      "import { Search, MessageSquare, CalendarRange, Share2 } from 'lucide-react';",
      '',
      'interface ControlsBarProps {',
      '  date: string;',
      '  division: string;',
      '  divisions: string[];',
      '  onDateChange: (date: string) => void;',
      '  onDivisionChange: (division: string) => void;',
      '  searchQuery: string;',
      '  onSearchChange: (q: string) => void;',
      "  onOpenReport: (mode: 'dpjp' | 'all') => void;",
      '  onOpenWeekly: () => void;',
      '}',
      '',
      'export function ControlsBar({',
      '  date,',
      '  division,',
      '  divisions,',
      '  onDateChange,',
      '  onDivisionChange,',
      '  searchQuery,',
      '  onSearchChange,',
      '  onOpenReport,',
      '  onOpenWeekly',
      '}: ControlsBarProps) {',
      '  return (',
      '    <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm space-y-3">',
      '      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 items-end">',
      '        <div>',
      '          <label className="block text-xs font-bold text-slate-700 mb-1">Tanggal Sweeping</label>',
      '          <input',
      '            type="date"',
      '            value={date}',
      '            onChange={(e) => onDateChange(e.target.value)}',
      '            className="w-full bg-slate-50 border border-slate-300 rounded-lg px-3 py-2 text-xs sm:text-sm font-medium focus:bg-white focus:outline-none focus:border-blue-500"',
      '          />',
      '        </div>',
      '        <div>',
      '          <label className="block text-xs font-bold text-slate-700 mb-1">Divisi Bedah</label>',
      '          <select',
      '            value={division}',
      '            onChange={(e) => onDivisionChange(e.target.value)}',
      '            className="w-full bg-slate-50 border border-slate-300 rounded-lg px-3 py-2 text-xs sm:text-sm font-medium focus:bg-white focus:outline-none focus:border-blue-500"',
      '          >',
      '            {divisions.map((d) => (',
      '              <option key={d} value={d}>{d}</option>',
      '            ))}',
      '          </select>',
      '        </div>',
      '        <div className="sm:col-span-2 lg:col-span-2">',
      '          <label className="block text-xs font-bold text-slate-700 mb-1">Cari Pasien (Nama, RM, Diagnosis)</label>',
      '          <div className="relative">',
      '            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />',
      '            <input',
      '              type="text"',
      '              value={searchQuery}',
      '              onChange={(e) => onSearchChange(e.target.value)}',
      '              placeholder="Ketik kata kunci..."',
      '              className="w-full bg-slate-50 border border-slate-300 rounded-lg pl-9 pr-3 py-2 text-xs sm:text-sm focus:bg-white focus:outline-none focus:border-blue-500"',
      '            />',
      '          </div>',
      '        </div>',
      '      </div>',
      '      <div className="pt-2 border-t border-slate-100 flex flex-wrap items-center justify-between gap-2">',
      '        <span className="text-xs text-slate-500 font-medium">Aksi Cepat:</span>',
      '        <div className="flex flex-wrap items-center gap-2">',
      '          <button',
      "            onClick={() => onOpenReport('dpjp')}",
      '            className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 font-semibold text-xs rounded-lg border border-blue-200 transition-colors"',
      '          >',
      '            <MessageSquare className="w-3.5 h-3.5" />',
      '            <span>WhatsApp DPJP</span>',
      '          </button>',
      '          <button',
      "            onClick={() => onOpenReport('all')}",
      '            className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 font-semibold text-xs rounded-lg border border-blue-200 transition-colors"',
      '          >',
      '            <Share2 className="w-3.5 h-3.5" />',
      '            <span>WhatsApp Divisi</span>',
      '          </button>',
      '          <button',
      '            onClick={onOpenWeekly}',
      '            className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 font-semibold text-xs rounded-lg border border-emerald-200 transition-colors"',
      '          >',
      '            <CalendarRange className="w-3.5 h-3.5" />',
      '            <span>Rekap Mingguan & CSV</span>',
      '          </button>',
      '        </div>',
      '      </div>',
      '    </div>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'components/PatientCard.tsx',
    description: 'Komponen kartu data pasien dengan informasi lengkap dan aksi',
    language: 'tsx',
    content: [
      "'use client';",
      '',
      "import { Patient } from '@/types';",
      "import { Edit2, Trash2, Stethoscope } from 'lucide-react';",
      '',
      'interface PatientCardProps {',
      '  patient: Patient;',
      '  onEdit: () => void;',
      '  onDelete: () => void;',
      '}',
      '',
      'export function PatientCard({ patient, onEdit, onDelete }: PatientCardProps) {',
      "  const isMale = patient.jk === 'L';",
      '  return (',
      '    <div className="bg-white border border-slate-200 rounded-xl p-3.5 shadow-xs hover:border-slate-300 transition-all flex flex-col justify-between">',
      '      <div>',
      '        <div className="flex items-start justify-between gap-2">',
      '          <div>',
      '            <h4 className="font-bold text-sm text-slate-900 leading-snug">{patient.name}</h4>',
      '            <div className="flex items-center gap-2 mt-1">',
      '              <span className={"text-[10px] font-bold px-2 py-0.5 rounded-full " + (isMale ? "bg-blue-100 text-blue-800" : "bg-rose-100 text-rose-800")}>',
      '                {patient.jk} · {patient.age || "Usia -"}',
      '              </span>',
      '              <span className="text-xs font-mono font-semibold text-slate-600 bg-slate-100 px-2 py-0.5 rounded">',
      '                RM: {patient.rm}',
      '              </span>',
      '            </div>',
      '          </div>',
      '          <span className="inline-block text-xs font-bold text-slate-800 bg-slate-100 border border-slate-200 px-2 py-0.5 rounded">',
      '            {patient.kamar || "-"}',
      '          </span>',
      '        </div>',
      '        <div className="mt-2.5 pt-2 border-t border-slate-100 text-xs text-slate-600 space-y-1">',
      '          <div className="flex items-center gap-1.5 text-slate-700 font-medium">',
      '            <Stethoscope className="w-3.5 h-3.5 text-blue-600 shrink-0" />',
      '            <span className="truncate">{patient.dpjp}</span>',
      '          </div>',
      '          <div className="text-slate-800 font-medium bg-slate-50 p-2 rounded-lg text-[11px] leading-relaxed">',
      '            {patient.dx || "Belum ada diagnosis."}',
      '          </div>',
      '        </div>',
      '      </div>',
      '      <div className="mt-3 pt-2 border-t border-slate-100 flex items-center justify-end">',
      '        <div className="flex items-center gap-1">',
      '          <button onClick={onEdit} className="p-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-colors">',
      '            <Edit2 className="w-3.5 h-3.5" />',
      '          </button>',
      '          <button onClick={onDelete} className="p-1.5 text-slate-500 hover:text-rose-600 hover:bg-rose-50 rounded-md transition-colors">',
      '            <Trash2 className="w-3.5 h-3.5" />',
      '          </button>',
      '        </div>',
      '      </div>',
      '    </div>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'components/PatientModal.tsx',
    description: 'Modal formulir input dan edit data pasien bedah',
    language: 'tsx',
    content: [
      "'use client';",
      '',
      "import { useState, useEffect } from 'react';",
      "import { Patient } from '@/types';",
      "import { DEFAULT_ROOMS } from '@/lib/constants';",
      "import { X } from 'lucide-react';",
      '',
      'interface PatientModalProps {',
      '  isOpen: boolean;',
      '  initialData: Patient | null;',
      '  defaultDpjp: string;',
      '  existingDpjps?: string[];',
      '  onClose: () => void;',
      '  onSave: (patient: Patient) => void;',
      '}',
      '',
      'export function PatientModal({ isOpen, initialData, defaultDpjp, onClose, onSave }: PatientModalProps) {',
      "  const [dpjp, setDpjp] = useState('');",
      "  const [room, setRoom] = useState('');",
      "  const [kamar, setKamar] = useState('');",
      "  const [name, setName] = useState('');",
      "  const [jk, setJk] = useState<'L' | 'P'>('L');",
      "  const [age, setAge] = useState('');",
      "  const [rm, setRm] = useState('');",
      "  const [dx, setDx] = useState('');",
      '',
      '  useEffect(() => {',
      '    if (initialData) {',
      '      setDpjp(initialData.dpjp || "");',
      '      setRoom(initialData.room || "");',
      '      setKamar(initialData.kamar || "");',
      '      setName(initialData.name || "");',
      '      setJk(initialData.jk || "L");',
      '      setAge(initialData.age || "");',
      '      setRm(initialData.rm || "");',
      '      setDx(initialData.dx || "");',
      '    } else {',
      '      setDpjp(defaultDpjp || "");',
      '      setRoom("SEROJA");',
      '      setKamar("");',
      '      setName("");',
      '      setJk("L");',
      '      setAge("");',
      '      setRm("");',
      '      setDx("");',
      '    }',
      '  }, [initialData, defaultDpjp, isOpen]);',
      '',
      '  if (!isOpen) return null;',
      '',
      '  const handleSubmit = (e: React.FormEvent) => {',
      '    e.preventDefault();',
      '    if (!name.trim() || !rm.trim()) return;',
      '    onSave({',
      '      id: initialData ? initialData.id : crypto.randomUUID(),',
      '      dpjp: dpjp.trim() || "dr. DPJP, Sp.B",',
      '      room: room.trim() || "SEROJA",',
      '      kamar: kamar.trim(),',
      '      name: name.trim(),',
      '      jk,',
      '      age: age.trim(),',
      '      rm: rm.trim(),',
      '      dx: dx.trim(),',
      '      updatedAt: new Date().toISOString()',
      '    });',
      '  };',
      '',
      '  return (',
      '    <div className="fixed inset-0 z-50 bg-slate-900/60 flex items-center justify-center p-4">',
      '      <div className="bg-white rounded-2xl max-w-xl w-full p-6 shadow-2xl border border-slate-200">',
      '        <div className="flex items-center justify-between pb-4 border-b border-slate-100">',
      '          <h2 className="text-lg font-bold text-slate-900">{initialData ? "Edit Pasien" : "Tambah Pasien"}</h2>',
      '          <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-slate-600"><X className="w-5 h-5" /></button>',
      '        </div>',
      '        <form onSubmit={handleSubmit} className="mt-4 space-y-3 text-xs">',
      '          <div className="grid grid-cols-2 gap-3">',
      '            <div>',
      '              <label className="block font-bold mb-1">DPJP *</label>',
      '              <input type="text" required value={dpjp} onChange={e => setDpjp(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg" placeholder="dr. Andi, Sp.U" />',
      '            </div>',
      '            <div>',
      '              <label className="block font-bold mb-1">Ruangan *</label>',
      '              <input type="text" required list="rList" value={room} onChange={e => setRoom(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg" placeholder="IGD / SEROJA / ICU" />',
      '              <datalist id="rList">{DEFAULT_ROOMS.map(r => <option key={r} value={r} />)}</datalist>',
      '            </div>',
      '            <div className="col-span-2">',
      '              <label className="block font-bold mb-1">Kamar / Bed</label>',
      '              <input type="text" value={kamar} onChange={e => setKamar(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg" placeholder="K201 / Bed 4" />',
      '            </div>',
      '            <div className="col-span-2">',
      '              <label className="block font-bold mb-1">Nama Pasien *</label>',
      '              <input type="text" required value={name} onChange={e => setName(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg" />',
      '            </div>',
      '            <div>',
      '              <label className="block font-bold mb-1">Jenis Kelamin</label>',
      '              <div className="flex gap-4 py-2">',
      '                <label><input type="radio" name="p_jk" checked={jk === "L"} onChange={() => setJk("L")} /> L</label>',
      '                <label><input type="radio" name="p_jk" checked={jk === "P"} onChange={() => setJk("P")} /> P</label>',
      '              </div>',
      '            </div>',
      '            <div>',
      '              <label className="block font-bold mb-1">Usia</label>',
      '              <input type="text" value={age} onChange={e => setAge(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg" placeholder="45 th" />',
      '            </div>',
      '            <div className="col-span-2">',
      '              <label className="block font-bold mb-1">Nomor RM *</label>',
      '              <input type="text" required value={rm} onChange={e => setRm(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg font-mono" />',
      '            </div>',
      '            <div className="col-span-2">',
      '              <label className="block font-bold mb-1">Diagnosis & Catatan</label>',
      '              <textarea rows={3} value={dx} onChange={e => setDx(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg" />',
      '            </div>',
      '          </div>',
      '          <div className="pt-3 border-t flex justify-end gap-2">',
      '            <button type="button" onClick={onClose} className="px-4 py-2 border rounded-lg">Batal</button>',
      '            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded-lg font-semibold">Simpan</button>',
      '          </div>',
      '        </form>',
      '      </div>',
      '    </div>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'components/ReportModal.tsx',
    description: 'Modal generator laporan WhatsApp untuk DPJP & Divisi',
    language: 'tsx',
    content: [
      "'use client';",
      '',
      "import { useState } from 'react';",
      "import { Patient } from '@/types';",
      "import { generateReportText } from '@/lib/storage';",
      "import { DEFAULT_ROOMS } from '@/lib/constants';",
      "import { X, Copy, Check, Send } from 'lucide-react';",
      '',
      'interface ReportModalProps {',
      '  isOpen: boolean;',
      "  mode: 'dpjp' | 'all';",
      '  date: string;',
      '  division: string;',
      '  koasName: string;',
      '  selectedDpjp: string;',
      '  patients: Patient[];',
      '  onClose: () => void;',
      '}',
      '',
      'export function ReportModal({ isOpen, mode, date, division, koasName, selectedDpjp, patients, onClose }: ReportModalProps) {',
      '  const [copied, setCopied] = useState(false);',
      '  if (!isOpen) return null;',
      '',
      '  const reportText = generateReportText({ mode, date, division, koasName, selectedDpjp, patients, allRooms: DEFAULT_ROOMS });',
      '',
      '  const handleCopy = async () => {',
      '    try {',
      '      await navigator.clipboard.writeText(reportText);',
      '      setCopied(true);',
      '      setTimeout(() => setCopied(false), 2000);',
      '    } catch {',
      '      alert("Gagal menyalin otomatis.");',
      '    }',
      '  };',
      '',
      '  return (',
      '    <div className="fixed inset-0 z-50 bg-slate-900/60 flex items-center justify-center p-4">',
      '      <div className="bg-white rounded-2xl max-w-2xl w-full p-6 shadow-2xl border border-slate-200 max-h-[90vh] flex flex-col">',
      '        <div className="flex items-center justify-between pb-3 border-b">',
      '          <h2 className="text-lg font-bold">{mode === "dpjp" ? "Laporan WhatsApp DPJP" : "Laporan WhatsApp Divisi"}</h2>',
      '          <button onClick={onClose} className="p-1 text-slate-400 hover:text-slate-600"><X className="w-5 h-5" /></button>',
      '        </div>',
      '        <div className="mt-4 flex-1 overflow-auto bg-slate-900 text-slate-200 p-4 rounded-xl font-mono text-xs whitespace-pre-wrap">',
      '          {reportText}',
      '        </div>',
      '        <div className="mt-4 pt-3 border-t flex justify-between items-center">',
      '          <span className="text-xs text-slate-500">{copied ? "Tersalin ke clipboard!" : "Siap dikirim ke WhatsApp"}</span>',
      '          <div className="flex gap-2">',
      '            <button onClick={handleCopy} className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 text-white rounded-lg text-xs font-semibold">',
      '              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}',
      '              <span>{copied ? "Tersalin" : "Copy to Clipboard"}</span>',
      '            </button>',
      '            <button onClick={() => window.open("https://api.whatsapp.com/send?text=" + encodeURIComponent(reportText), "_blank")} className="flex items-center gap-1.5 px-4 py-2 bg-emerald-600 text-white rounded-lg text-xs font-semibold">',
      '              <Send className="w-4 h-4" />',
      '              <span>Buka WhatsApp</span>',
      '            </button>',
      '          </div>',
      '        </div>',
      '      </div>',
      '    </div>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'components/WeeklyModal.tsx',
    description: 'Modal rekapitulasi sweeping mingguan dengan tabel lintas hari dan export CSV',
    language: 'tsx',
    content: [
      "'use client';",
      '',
      "import { useState, useEffect } from 'react';",
      "import { computeWeeklyRecap, exportWeeklyCSV } from '@/lib/storage';",
      "import { WeeklyRow } from '@/types';",
      "import { X, Download, RefreshCw } from 'lucide-react';",
      '',
      'interface WeeklyModalProps {',
      '  isOpen: boolean;',
      '  currentDate: string;',
      '  division: string;',
      '  onClose: () => void;',
      '}',
      '',
      'export function WeeklyModal({ isOpen, currentDate, division, onClose }: WeeklyModalProps) {',
      "  const [startDate, setStartDate] = useState('');",
      "  const [endDate, setEndDate] = useState('');",
      '  const [rows, setRows] = useState<WeeklyRow[]>([]);',
      '  const [dates, setDates] = useState<string[]>([]);',
      '',
      '  useEffect(() => {',
      '    if (!currentDate) return;',
      '    const d = new Date(currentDate + "T00:00:00");',
      '    const day = d.getDay();',
      '    const diff = (day + 6) % 7;',
      '    const mon = new Date(d);',
      '    mon.setDate(d.getDate() - diff);',
      '    const sun = new Date(mon);',
      '    sun.setDate(mon.getDate() + 6);',
      '    const s = mon.toISOString().slice(0, 10);',
      '    const e = sun.toISOString().slice(0, 10);',
      '    setStartDate(s);',
      '    setEndDate(e);',
      '    const res = computeWeeklyRecap(s, e, division);',
      '    setRows(res.rows);',
      '    setDates(res.dates);',
      '  }, [currentDate, division, isOpen]);',
      '',
      '  if (!isOpen) return null;',
      '',
      '  const handleGenerate = () => {',
      '    if (!startDate || !endDate) return;',
      '    const res = computeWeeklyRecap(startDate, endDate, division);',
      '    setRows(res.rows);',
      '    setDates(res.dates);',
      '  };',
      '',
      '  return (',
      '    <div className="fixed inset-0 z-50 bg-slate-900/60 flex items-center justify-center p-4">',
      '      <div className="bg-white rounded-2xl max-w-5xl w-full p-6 shadow-2xl border border-slate-200 max-h-[92vh] flex flex-col">',
      '        <div className="flex items-center justify-between pb-3 border-b">',
      '          <h2 className="text-lg font-bold text-slate-900">Rekapitulasi Mingguan Pasien</h2>',
      '          <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-slate-600"><X className="w-5 h-5" /></button>',
      '        </div>',
      '        <div className="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3 items-end">',
      '          <div>',
      '            <label className="block text-xs font-bold mb-1">Mulai</label>',
      '            <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg text-xs" />',
      '          </div>',
      '          <div>',
      '            <label className="block text-xs font-bold mb-1">Akhir</label>',
      '            <input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} className="w-full bg-slate-50 border p-2 rounded-lg text-xs" />',
      '          </div>',
      '          <div className="flex gap-2">',
      '            <button onClick={handleGenerate} className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 bg-blue-600 text-white font-semibold text-xs rounded-lg">',
      '              <RefreshCw className="w-3.5 h-3.5" /> Hitung',
      '            </button>',
      '            {rows.length > 0 && (',
      '              <button onClick={() => exportWeeklyCSV(rows, dates, division, startDate, endDate)} className="flex items-center gap-1.5 px-3 py-2 bg-emerald-600 text-white font-semibold text-xs rounded-lg">',
      '                <Download className="w-3.5 h-3.5" /> Export CSV',
      '              </button>',
      '            )}',
      '          </div>',
      '        </div>',
      '        <div className="mt-4 flex-1 overflow-auto border rounded-xl">',
      '          {rows.length === 0 ? (',
      '            <div className="p-8 text-center text-xs text-slate-500">Tidak ada data pasien pada rentang tanggal ini.</div>',
      '          ) : (',
      '            <table className="w-full text-left text-xs border-collapse">',
      '              <thead>',
      '                <tr className="bg-slate-100 border-b">',
      '                  <th className="p-2.5 font-bold">No</th>',
      '                  <th className="p-2.5 font-bold">No. RM</th>',
      '                  <th className="p-2.5 font-bold">Nama Pasien</th>',
      '                  <th className="p-2.5 font-bold">JK</th>',
      '                  <th className="p-2.5 font-bold">Usia</th>',
      '                  <th className="p-2.5 font-bold">DPJP</th>',
      '                  <th className="p-2.5 font-bold">Ruangan Terakhir</th>',
      '                  <th className="p-2.5 font-bold">Diagnosis</th>',
      '                  {dates.map(dt => (',
      '                    <th key={dt} className="p-2.5 font-bold text-center border-l">',
      '                      {new Date(dt + "T00:00:00").toLocaleDateString("id-ID", { weekday: "short", day: "2-digit" })}',
      '                    </th>',
      '                  ))}',
      '                </tr>',
      '              </thead>',
      '              <tbody className="divide-y divide-slate-100">',
      '                {rows.map((row, idx) => (',
      '                  <tr key={row.rm} className="hover:bg-slate-50">',
      '                    <td className="p-2.5 font-semibold text-slate-500">{idx + 1}</td>',
      '                    <td className="p-2.5 font-mono font-medium text-blue-700">{row.rm}</td>',
      '                    <td className="p-2.5 font-bold text-slate-900">{row.name}</td>',
      '                    <td className="p-2.5">{row.jk}</td>',
      '                    <td className="p-2.5">{row.age}</td>',
      '                    <td className="p-2.5 text-slate-700">{row.dpjp}</td>',
      '                    <td className="p-2.5 font-medium">{row.lastRoom} {row.lastKamar ? "/ " + row.lastKamar : ""}</td>',
      '                    <td className="p-2.5 max-w-xs truncate text-slate-600">{row.dx}</td>',
      '                    {dates.map(dt => (',
      '                      <td key={dt} className="p-2.5 text-center font-mono text-[11px] border-l">',
      '                        {row.days[dt] ? <span className="text-emerald-700 font-semibold">{row.days[dt]}</span> : <span className="text-slate-300">-</span>}',
      '                      </td>',
      '                    ))}',
      '                  </tr>',
      '                ))}',
      '              </tbody>',
      '            </table>',
      '          )}',
      '        </div>',
      '      </div>',
      '    </div>',
      '  );',
      '}'
    ].join('\n')
  },
  {
    path: 'lib/constants.ts',
    description: 'Daftar divisi bedah dan daftar default ruangan rawat inap',
    language: 'ts',
    content: [
      'export const DIVISIONS: string[] = [',
      "  'Bedah Digestif & Umum',",
      "  'Bedah Anak',",
      "  'Urologi',",
      "  'Ortopedi',",
      "  'Bedah Saraf',",
      "  'BTKV',",
      "  'Bedah Plastik',",
      "  'Bedah Onkologi'",
      '];',
      '',
      'export const DEFAULT_ROOMS: string[] = [',
      "  'IGD',",
      "  'SEROJA',",
      "  'ICU',",
      "  'ICCU',",
      "  'PICU',",
      "  'NICU',",
      "  'MAWAR',",
      "  'TERATAI',",
      "  'ANGGREK'",
      '];'
    ].join('\n')
  },
  {
    path: 'lib/storage.ts',
    description: 'Utilitas penyimpanan local data, laporan WhatsApp, dan export CSV',
    language: 'ts',
    content: [
      "import { Patient, WeeklyRow } from '@/types';",
      '',
      "const KEY_PREFIX = 'sweepinganku';",
      '',
      'export function getStorageKey(date: string, division: string): string {',
      '  return KEY_PREFIX + ":" + date + ":" + division;',
      '}',
      '',
      'export function today(): string {',
      '  return new Date().toISOString().slice(0, 10);',
      '}',
      '',
      'export function formatIndonesianDate(dateStr: string): string {',
      "  if (!dateStr) return '';",
      '  try {',
      '    const d = new Date(dateStr + "T00:00:00");',
      '    return d.toLocaleDateString("id-ID", {',
      '      day: "2-digit",',
      '      month: "long",',
      '      year: "numeric"',
      '    });',
      '  } catch {',
      '    return dateStr;',
      '  }',
      '}',
      '',
      'export function loadPatients(date: string, division: string): Patient[] {',
      "  if (typeof window === 'undefined') return [];",
      '  const raw = localStorage.getItem(getStorageKey(date, division));',
      '  if (raw) {',
      '    try {',
      '      return JSON.parse(raw);',
      '    } catch {',
      '      return [];',
      '    }',
      '  }',
      '  return [];',
      '}',
      '',
      'export function savePatients(date: string, division: string, patients: Patient[]): void {',
      "  if (typeof window === 'undefined') return;",
      '  localStorage.setItem(getStorageKey(date, division), JSON.stringify(patients));',
      '}',
      '',
      'export function getKoasName(): string {',
      "  if (typeof window === 'undefined') return 'dr. Muda / Koas Bedah';",
      "  return localStorage.getItem(KEY_PREFIX + ':koasName') || 'dr. Muda / Koas Bedah';",
      '}',
      '',
      'export function setKoasName(name: string): void {',
      "  if (typeof window === 'undefined') return;",
      "  localStorage.setItem(KEY_PREFIX + ':koasName', name);",
      '}',
      '',
      'export function generateReportText({',
      '  mode,',
      '  date,',
      '  division,',
      '  koasName,',
      '  selectedDpjp,',
      '  patients,',
      '  allRooms',
      '}: {',
      "  mode: 'dpjp' | 'all';",
      '  date: string;',
      '  division: string;',
      '  koasName: string;',
      '  selectedDpjp?: string;',
      '  patients: Patient[];',
      '  allRooms: string[];',
      '}): string {',
      '  const d = new Date(date + "T00:00:00");',
      '  const dayName = d.toLocaleDateString("id-ID", {',
      '    weekday: "long",',
      '    day: "2-digit",',
      '    month: "long",',
      '    year: "numeric"',
      '  });',
      '',
      '  const header = "Selamat pagi, dokter. Mohon maaf mengganggu waktunya, dokter.\\n" +',
      '    "Perkenalkan, dokter, saya " + (koasName || "[Nama Koas]") + " selaku dokter muda yang saat ini sedang menjalani stase bedah Divisi " + division + ".\\n" +',
      '    "Mohon izin untuk melaporkan pasien dokter di ruangan rawat inap pada hari ini, dokter. 🙏🏻\\n\\n" +',
      '    "*" + dayName + "*";',
      '',
      '  const closing = "\\n\\nMohon maaf jika terdapat kesalahan, dokter. Terima kasih, dokter. 🙏🏻";',
      '',
      '  let filtered = patients;',
      '  if (mode === "dpjp") {',
      '    const targetDpjp = selectedDpjp || (patients.length > 0 ? patients[0].dpjp : "[DPJP]");',
      '    filtered = patients.filter(p => p.dpjp === targetDpjp);',
      '    let out = header + "\\n*DPJP: " + targetDpjp + "*\\n*Total pasien: " + filtered.length + " pasien*\\n";',
      '    out += formatRoomsReport(filtered, false, allRooms);',
      '    out += closing;',
      '    return out;',
      '  } else {',
      '    let out = header + "\\n*Total pasien keseluruhan: " + filtered.length + " pasien*\\n";',
      '    out += formatRoomsReport(filtered, true, allRooms);',
      '    out += closing;',
      '    return out;',
      '  }',
      '}',
      '',
      'function formatRoomsReport(patients: Patient[], withDpjp: boolean, defaultRooms: string[]): string {',
      '  const patientRooms = [...new Set(patients.map(p => p.room))];',
      '  const sortedRooms = [',
      '    ...defaultRooms.filter(r => patientRooms.includes(r)),',
      '    ...patientRooms.filter(r => !defaultRooms.includes(r))',
      '  ];',
      '  if (sortedRooms.length === 0) {',
      '    return "\\n(Belum ada pasien yang terdaftar di ruangan rawat inap)";',
      '  }',
      '  return sortedRooms.map(r => {',
      '    const roomPatients = patients.filter(p => p.room === r);',
      '    if (roomPatients.length === 0) return "";',
      '    const lines = roomPatients',
      '      .map((p, i) => (i + 1) + ". " + (p.kamar || "-") + " / " + p.name + " / " + (p.jk || "-") + " / " + (p.age || "-") + " / RM: " + p.rm + " / Dx: " + (p.dx || "-") + (withDpjp ? " / DPJP: " + p.dpjp : ""))',
      '      .join("\\n");',
      '    return "\\n*" + r + " (" + roomPatients.length + ")*\\n────────────────────\\n" + lines;',
      '  }).filter(Boolean).join("\\n");',
      '}',
      '',
      'export function computeWeeklyRecap(startDate: string, endDate: string, division: string): {',
      '  rows: WeeklyRow[];',
      '  dates: string[];',
      '} {',
      '  const dates: string[] = [];',
      '  const current = new Date(startDate + "T00:00:00");',
      '  const stop = new Date(endDate + "T00:00:00");',
      '  while (current <= stop) {',
      '    dates.push(current.toISOString().slice(0, 10));',
      '    current.setDate(current.getDate() + 1);',
      '  }',
      '',
      '  const map = new Map<string, WeeklyRow>();',
      '  dates.forEach(dt => {',
      '    const raw = localStorage.getItem(getStorageKey(dt, division));',
      '    if (!raw) return;',
      '    try {',
      '      const dayPatients: Patient[] = JSON.parse(raw);',
      '      dayPatients.forEach(p => {',
      '        if (!p.rm) return;',
      '        let r = map.get(p.rm);',
      '        if (!r) {',
      '          r = {',
      '            rm: p.rm,',
      '            name: p.name,',
      '            jk: p.jk || "-",',
      '            age: p.age || "-",',
      '            dpjp: p.dpjp,',
      '            dx: p.dx || "",',
      '            first: dt,',
      '            last: dt,',
      '            lastRoom: p.room,',
      '            lastKamar: p.kamar || "",',
      '            days: {}',
      '          };',
      '          map.set(p.rm, r);',
      '        }',
      '        r.name = p.name;',
      '        r.jk = p.jk;',
      '        r.age = p.age;',
      '        r.dpjp = p.dpjp;',
      '        r.dx = p.dx;',
      '        r.last = dt;',
      '        r.lastRoom = p.room;',
      '        r.lastKamar = p.kamar;',
      '        r.days[dt] = p.room + (p.kamar ? " / " + p.kamar : "");',
      '      });',
      '    } catch {}',
      '  });',
      '',
      '  return { rows: [...map.values()].sort((a, b) => a.name.localeCompare(b.name)), dates };',
      '}',
      '',
      'export function exportWeeklyCSV(rows: WeeklyRow[], dates: string[], division: string, startDate: string, endDate: string): void {',
      '  if (!rows.length) return;',
      '  const dayHeaders = dates.map(x => {',
      '    const d = new Date(x + "T00:00:00");',
      '    return d.toLocaleDateString("id-ID", { weekday: "short", day: "2-digit", month: "2-digit" });',
      '  });',
      '',
      '  const headers = [',
      '    "No",',
      '    "No. RM",',
      '    "Nama Pasien",',
      '    "Jenis Kelamin",',
      '    "Usia",',
      '    "DPJP",',
      '    "Ruangan Terakhir / Kamar",',
      '    "Diagnosis",',
      '    "Tgl Pertama Sweeping",',
      '    "Tgl Terakhir Sweeping",',
      '    ...dayHeaders',
      '  ];',
      '',
      '  const csvRows = [',
      '    headers,',
      '    ...rows.map((r, i) => [',
      '      i + 1,',
      '      r.rm,',
      '      r.name,',
      '      r.jk,',
      '      r.age,',
      '      r.dpjp,',
      '      r.lastRoom + " / " + (r.lastKamar || "-"),',
      '      r.dx,',
      '      r.first,',
      '      r.last,',
      '      ...dates.map(d => r.days[d] || "-")',
      '    ])',
      '  ];',
      '',
      '  const csvContent = csvRows',
      '    .map(row => row.map(v => "\\"" + String(v ?? "").replace(/"/g, \'""\') + "\\"").join(","))',
      '    .join("\\n");',
      '',
      '  const blob = new Blob(["\\ufeff" + csvContent], { type: "text/csv;charset=utf-8;" });',
      '  const url = URL.createObjectURL(blob);',
      '  const link = document.createElement("a");',
      '  link.href = url;',
      '  link.download = "rekap-sweeping-" + division.replace(/\\s+/g, "-") + "-" + startDate + "_" + endDate + ".csv";',
      '  document.body.appendChild(link);',
      '  link.click();',
      '  document.body.removeChild(link);',
      '  URL.revokeObjectURL(url);',
      '}'
    ].join('\n')
  },
  {
    path: 'types/index.ts',
    description: 'Definisi antarmuka TypeScript untuk Pasien, View, dan Baris Rekap',
    language: 'ts',
    content: [
      'export interface Patient {',
      '  id: string;',
      '  dpjp: string;',
      '  room: string;',
      '  kamar: string;',
      '  name: string;',
      "  jk: 'L' | 'P';",
      '  age: string;',
      '  rm: string;',
      '  dx: string;',
      '  updatedAt: string;',
      '}',
      '',
      "export type ViewMode = 'dpjp' | 'all';",
      '',
      'export interface WeeklyRow {',
      '  rm: string;',
      '  name: string;',
      '  jk: string;',
      '  age: string;',
      '  dpjp: string;',
      '  dx: string;',
      '  first: string;',
      '  last: string;',
      '  lastRoom: string;',
      '  lastKamar: string;',
      '  days: Record<string, string>;',
      '}'
    ].join('\n')
  },
  {
    path: 'next.config.mjs',
    description: 'Konfigurasi Next.js',
    language: 'javascript',
    content: [
      '/** @type {import("next").NextConfig} */',
      'const nextConfig = {',
      '  reactStrictMode: true,',
      '};',
      '',
      'export default nextConfig;'
    ].join('\n')
  },
  {
    path: 'tsconfig.json',
    description: 'Konfigurasi TypeScript Next.js dengan path alias @/*',
    language: 'json',
    content: [
      '{',
      '  "compilerOptions": {',
      '    "target": "ES2017",',
      '    "lib": ["dom", "dom.iterable", "esnext"],',
      '    "allowJs": true,',
      '    "skipLibCheck": true,',
      '    "strict": true,',
      '    "noEmit": true,',
      '    "esModuleInterop": true,',
      '    "module": "esnext",',
      '    "moduleResolution": "bundler",',
      '    "resolveJsonModule": true,',
      '    "isolatedModules": true,',
      '    "jsx": "preserve",',
      '    "incremental": true,',
      '    "plugins": [',
      '      {',
      '        "name": "next"',
      '      }',
      '    ],',
      '    "paths": {',
      '      "@/*": ["./*"]',
      '    }',
      '  },',
      '  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],',
      '  "exclude": ["node_modules"]',
      '}'
    ].join('\n')
  },
  {
    path: 'tailwind.config.ts',
    description: 'Konfigurasi Tailwind CSS untuk Next.js App Router',
    language: 'typescript',
    content: [
      'import type { Config } from "tailwindcss";',
      '',
      'const config: Config = {',
      '  content: [',
      '    "./pages/**/*.{js,ts,jsx,tsx,mdx}",',
      '    "./components/**/*.{js,ts,jsx,tsx,mdx}",',
      '    "./app/**/*.{js,ts,jsx,tsx,mdx}",',
      '  ],',
      '  theme: {',
      '    extend: {},',
      '  },',
      '  plugins: [],',
      '};',
      'export default config;'
    ].join('\n')
  },
  {
    path: 'postcss.config.mjs',
    description: 'Konfigurasi PostCSS untuk Tailwind CSS',
    language: 'javascript',
    content: [
      'const config = {',
      '  plugins: {',
      '    tailwindcss: {},',
      '    autoprefixer: {},',
      '  },',
      '};',
      'export default config;'
    ].join('\n')
  },
  {
    path: 'README.md',
    description: 'Panduan lengkap instalasi dan menjalankan repositori Next.js Sweepinganku',
    language: 'markdown',
    content: [
      '# Sweepinganku — Surgical Sweeping Manager (Next.js App Router)',
      '',
      'Repositori ini adalah hasil konversi dari aplikasi web HTML menjadi proyek **Next.js 15 (App Router)** dengan **TypeScript** dan **Tailwind CSS**.',
      '',
      '## ✨ Fitur',
      '- **Manajemen Pasien Bedah**: Input data pasien per ruangan (IGD, ICU, SEROJA, bangsal), kamar/bed, RM, DPJP, dan diagnosis klinis.',
      '- **Laporan WhatsApp Otomatis**: Format per-DPJP dan seluruh divisi dengan 1-klik salin & buka WhatsApp.',
      '- **Rekapitulasi Mingguan**: Tabel cross-tabulation pasien per hari dan ekspor ke CSV (Excel).',
      '',
      '## 🚀 Cara Menjalankan',
      '',
      '### 1. Ekstrak & Masuk ke Folder Proyek',
      '```bash',
      'cd sweepinganku-nextjs',
      '```',
      '',
      '### 2. Install Dependensi',
      '```bash',
      'npm install',
      '```',
      '',
      '### 3. Jalankan Mode Development',
      '```bash',
      'npm run dev',
      '```',
      'Buka browser di http://localhost:3000.',
      '',
      '### 4. Build untuk Production',
      '```bash',
      'npm run build',
      'npm run start',
      '```'
    ].join('\n')
  }
];

export async function downloadNextjsProjectZip(): Promise<void> {
  const zip = new JSZip();
  const root = zip.folder('sweepinganku-nextjs');
  if (!root) return;

  for (const file of NEXTJS_REPO_FILES) {
    root.file(file.path, file.content);
  }

  const content = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(content);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'sweepinganku-nextjs-repo.zip';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
